/**
 * Mock Test Data: 10 Todo items in 'queue' status (status: "todo")
 * Used for testing UI responsiveness and sync interruption features
 */

import type { Todo } from "../types";

export const mockQueueTodos: Todo[] = [
  {
    id: "T-001",
    title: "Review documentation for API v2 release",
    description: "Go through all endpoint documentation and verify accuracy before public release",
    status: "todo",
    priority: "high",
    dueDate: "2025-12-12T10:00:00.000Z",
    estimatedTime: 120,
    actualTime: null,
    contextId: null,
    sourceType: "chat",
    sourceId: "msg-001",
    sourceSpaceId: "space-dev-team",
    sourceMessageId: "msg-001",
    sourceSpaceName: "Development Team",
    sourceThreadName: ["API Discussion"],
    templateId: null,
    tags: ["documentation", "api"],
    eisenhower: "urgent_important",
    completedAt: null,
    createdAt: "2025-12-09T08:00:00.000Z",
    updatedAt: "2025-12-09T08:00:00.000Z",
    subtasks: [],
    assigneeId: "user-101",
    assigneeName: "Alice Johnson",
    senderName: "Bob Smith",
    senderEmail: "bob.smith@example.com",
  },
  {
    id: "T-002",
    title: "Deploy hotfix for authentication bug",
    description: "Critical fix for login timeout issue affecting production users",
    status: "todo",
    priority: "urgent",
    dueDate: "2025-12-10T14:00:00.000Z",
    estimatedTime: 60,
    actualTime: null,
    contextId: null,
    sourceType: "chat",
    sourceId: "msg-002",
    sourceSpaceId: "space-ops",
    sourceMessageId: "msg-002",
    sourceSpaceName: "Operations",
    sourceThreadName: ["Incident Response"],
    templateId: null,
    tags: ["hotfix", "production", "urgent"],
    eisenhower: "urgent_important",
    completedAt: null,
    createdAt: "2025-12-09T07:30:00.000Z",
    updatedAt: "2025-12-09T07:30:00.000Z",
    subtasks: [],
    assigneeId: "user-102",
    assigneeName: "Charlie Davis",
    senderName: "Diana Evans",
    senderEmail: "diana.evans@example.com",
  },
  {
    id: "T-003",
    title: "Run automated regression tests",
    description: "Execute full test suite before sprint release",
    status: "todo",
    priority: "medium",
    dueDate: "2025-12-11T16:00:00.000Z",
    estimatedTime: 90,
    actualTime: null,
    contextId: null,
    sourceType: "chat",
    sourceId: "msg-003",
    sourceSpaceId: "space-qa",
    sourceMessageId: "msg-003",
    sourceSpaceName: "QA Team",
    sourceThreadName: ["Sprint Testing"],
    templateId: null,
    tags: ["testing", "automation"],
    eisenhower: "not_urgent_important",
    completedAt: null,
    createdAt: "2025-12-09T09:00:00.000Z",
    updatedAt: "2025-12-09T09:00:00.000Z",
    subtasks: [],
    assigneeId: "user-103",
    assigneeName: "Eva Martinez",
    senderName: "Frank Wilson",
    senderEmail: "frank.wilson@example.com",
  },
  {
    id: "T-004",
    title: "Update database migration scripts",
    description: "Prepare migration scripts for new user preferences schema",
    status: "todo",
    priority: "high",
    dueDate: "2025-12-13T09:00:00.000Z",
    estimatedTime: 180,
    actualTime: null,
    contextId: null,
    sourceType: "chat",
    sourceId: "msg-004",
    sourceSpaceId: "space-backend",
    sourceMessageId: "msg-004",
    sourceSpaceName: "Backend Team",
    sourceThreadName: ["Database Updates"],
    templateId: null,
    tags: ["database", "migration"],
    eisenhower: "urgent_important",
    completedAt: null,
    createdAt: "2025-12-09T10:15:00.000Z",
    updatedAt: "2025-12-09T10:15:00.000Z",
    subtasks: [],
    assigneeId: "user-104",
    assigneeName: "George Brown",
    senderName: "Hannah Lee",
    senderEmail: "hannah.lee@example.com",
  },
  {
    id: "T-005",
    title: "Design review for new dashboard UI",
    description: "Review mockups and provide feedback on the analytics dashboard redesign",
    status: "todo",
    priority: "medium",
    dueDate: "2025-12-14T11:00:00.000Z",
    estimatedTime: 60,
    actualTime: null,
    contextId: null,
    sourceType: "chat",
    sourceId: "msg-005",
    sourceSpaceId: "space-design",
    sourceMessageId: "msg-005",
    sourceSpaceName: "Design Team",
    sourceThreadName: ["Dashboard Redesign"],
    templateId: null,
    tags: ["design", "review", "ui"],
    eisenhower: "not_urgent_important",
    completedAt: null,
    createdAt: "2025-12-09T11:00:00.000Z",
    updatedAt: "2025-12-09T11:00:00.000Z",
    subtasks: [],
    assigneeId: "user-105",
    assigneeName: "Ivy Chen",
    senderName: "Jack Taylor",
    senderEmail: "jack.taylor@example.com",
  },
  {
    id: "T-006",
    title: "Configure CI/CD pipeline for microservices",
    description: "Set up automated deployment pipeline for the new notification service",
    status: "todo",
    priority: "high",
    dueDate: "2025-12-12T15:00:00.000Z",
    estimatedTime: 240,
    actualTime: null,
    contextId: null,
    sourceType: "chat",
    sourceId: "msg-006",
    sourceSpaceId: "space-devops",
    sourceMessageId: "msg-006",
    sourceSpaceName: "DevOps",
    sourceThreadName: ["Infrastructure"],
    templateId: null,
    tags: ["devops", "ci-cd", "automation"],
    eisenhower: "urgent_important",
    completedAt: null,
    createdAt: "2025-12-09T08:45:00.000Z",
    updatedAt: "2025-12-09T08:45:00.000Z",
    subtasks: [],
    assigneeId: "user-106",
    assigneeName: "Kevin Park",
    senderName: "Laura White",
    senderEmail: "laura.white@example.com",
  },
  {
    id: "T-007",
    title: "Write unit tests for payment module",
    description: "Achieve 80% code coverage for the new payment processing module",
    status: "todo",
    priority: "medium",
    dueDate: "2025-12-15T17:00:00.000Z",
    estimatedTime: 300,
    actualTime: null,
    contextId: null,
    sourceType: "chat",
    sourceId: "msg-007",
    sourceSpaceId: "space-payments",
    sourceMessageId: "msg-007",
    sourceSpaceName: "Payments Team",
    sourceThreadName: ["Testing Coverage"],
    templateId: null,
    tags: ["testing", "unit-tests", "payments"],
    eisenhower: "not_urgent_important",
    completedAt: null,
    createdAt: "2025-12-09T12:00:00.000Z",
    updatedAt: "2025-12-09T12:00:00.000Z",
    subtasks: [],
    assigneeId: "user-107",
    assigneeName: "Maria Garcia",
    senderName: "Nathan Scott",
    senderEmail: "nathan.scott@example.com",
  },
  {
    id: "T-008",
    title: "Optimize image loading performance",
    description: "Implement lazy loading and WebP format for product images",
    status: "todo",
    priority: "low",
    dueDate: "2025-12-18T10:00:00.000Z",
    estimatedTime: 180,
    actualTime: null,
    contextId: null,
    sourceType: "chat",
    sourceId: "msg-008",
    sourceSpaceId: "space-frontend",
    sourceMessageId: "msg-008",
    sourceSpaceName: "Frontend Team",
    sourceThreadName: ["Performance"],
    templateId: null,
    tags: ["performance", "optimization", "frontend"],
    eisenhower: "not_urgent_not_important",
    completedAt: null,
    createdAt: "2025-12-09T13:30:00.000Z",
    updatedAt: "2025-12-09T13:30:00.000Z",
    subtasks: [],
    assigneeId: "user-108",
    assigneeName: "Oliver Kim",
    senderName: "Patricia Adams",
    senderEmail: "patricia.adams@example.com",
  },
  {
    id: "T-009",
    title: "Security audit for user data endpoints",
    description: "Conduct penetration testing and vulnerability assessment",
    status: "todo",
    priority: "urgent",
    dueDate: "2025-12-11T12:00:00.000Z",
    estimatedTime: 480,
    actualTime: null,
    contextId: null,
    sourceType: "chat",
    sourceId: "msg-009",
    sourceSpaceId: "space-security",
    sourceMessageId: "msg-009",
    sourceSpaceName: "Security Team",
    sourceThreadName: ["Audit Q4"],
    templateId: null,
    tags: ["security", "audit", "compliance"],
    eisenhower: "urgent_important",
    completedAt: null,
    createdAt: "2025-12-09T07:00:00.000Z",
    updatedAt: "2025-12-09T07:00:00.000Z",
    subtasks: [],
    assigneeId: "user-109",
    assigneeName: "Quinn Roberts",
    senderName: "Rachel Green",
    senderEmail: "rachel.green@example.com",
  },
  {
    id: "T-010",
    title: "Prepare sprint retrospective presentation",
    description: "Compile metrics and feedback for end-of-sprint review meeting",
    status: "todo",
    priority: "low",
    dueDate: "2025-12-16T14:00:00.000Z",
    estimatedTime: 45,
    actualTime: null,
    contextId: null,
    sourceType: "manual",
    sourceId: null,
    sourceSpaceId: null,
    sourceMessageId: null,
    sourceSpaceName: null,
    sourceThreadName: [],
    templateId: null,
    tags: ["meeting", "retrospective"],
    eisenhower: "not_urgent_not_important",
    completedAt: null,
    createdAt: "2025-12-09T14:00:00.000Z",
    updatedAt: "2025-12-09T14:00:00.000Z",
    subtasks: [],
    assigneeId: "user-110",
    assigneeName: "Sam Thompson",
    senderName: null,
    senderEmail: null,
  },
];

/**
 * Get mock todos by priority
 */
export const getMockTodosByPriority = (priority: string): Todo[] => {
  return mockQueueTodos.filter((todo) => todo.priority === priority);
};

/**
 * Get mock todos count summary
 */
export const getMockTodosSummary = () => ({
  total: mockQueueTodos.length,
  urgent: mockQueueTodos.filter((t) => t.priority === "urgent").length,
  high: mockQueueTodos.filter((t) => t.priority === "high").length,
  medium: mockQueueTodos.filter((t) => t.priority === "medium").length,
  low: mockQueueTodos.filter((t) => t.priority === "low").length,
});
